# Generated by Django 3.1.13 on 2021-08-23 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20210823_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_subscription', to='topic.topic'),
        ),
    ]
