version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"

  kafka1:
    image: wurstmeister/kafka
    hostname: kafka1
    ports:
     - "${KAFKA1_OUTSIDE_HOST_PORT:-9092}:${KAFKA1_OUTSIDE_HOST_PORT:-9092}"
    depends_on:
     - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "notification:1:1,mail:1:1,sms:1:1,in_app:1:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:19092,OUTSIDE://${OUTSIDE_HOST_IP:-192.168.0.105}:${KAFKA1_OUTSIDE_HOST_PORT:-9092}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:19092,OUTSIDE://0.0.0.0:${KAFKA1_OUTSIDE_HOST_PORT:-9092}
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    image: wurstmeister/kafka
    hostname: kafka2
    ports:
     - "${KAFKA2_OUTSIDE_HOST_PORT:-9093}:${KAFKA2_OUTSIDE_HOST_PORT:-9093}"
    depends_on:
     - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:19093,OUTSIDE://${OUTSIDE_HOST_IP:-192.168.0.105}:${KAFKA2_OUTSIDE_HOST_PORT:-9093}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:19093,OUTSIDE://0.0.0.0:${KAFKA2_OUTSIDE_HOST_PORT:-9093}
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
