version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: notification_validator_local_django
    container_name: validator_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8001:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: notification_validator_production_postgres
    container_name: validator_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: notification_validator_local_docs
    container_name: validator_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./notification_validator:/app/notification_validator:z
    ports:
      - "7001:7000"
    command: /start-docs

  redis:
    image: redis:6
    container_name: validator_redis

  celeryworker:
    <<: *django
    image: notification_validator_local_celeryworker
    container_name: validator_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: notification_validator_local_celerybeat
    container_name: validator_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: notification_validator_local_flower
    container_name: validator_flower
    ports:
      - "5555:5555"
    command: /start-flower
