# Generated by Django 3.1.13 on 2021-08-24 10:49

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Expiration Time')),
                ('time_to_live', models.PositiveIntegerField(blank=True, null=True, verbose_name='time to live')),
                ('message', models.JSONField(blank=True, null=True, verbose_name='message')),
                ('provider', models.CharField(blank=True, max_length=255, null=True, verbose_name='Provider')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=255, verbose_name='Priority')),
                ('users', models.JSONField(blank=True, null=True, verbose_name='Users list')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
